use_frameworks!

platform :ios, '10.0'

target 'LYWaterFlowLayout_Example' do
  pod 'LYWaterFlowLayout', :path => '../'

  target 'LYWaterFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
